version: "3.8"

services: 
  lider_app:
    container_name: "lider_app"
    image: applider:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://bd_posgresql:5432/certificadoslider
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=lider.2025
      - AWS_REGION=sa-east-1  # Solo la región es necesaria
      - AWS_PROFILE=default
#      - AWS_S3_ACCESS_KEY=AKIAXWMANA327N4EGHK
#      - AWS_S3_SECRET_KEY=AT2TwmdW+7IdBmy03b5cq3lNvaVyNkriRFAIgzpt
      
    #  - JAVA_OPTS=-Xms512m -Xmx2g  # Aumentar memoria de la JVM
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=80.0  # Permite ajuste dinámico de memoria
    depends_on:
      - bd_posgresql
    volumes:
#      - ${HOME}/.aws:/root/.aws  # Monta las credenciales de AWS dentro del contenedor
      - ~/.aws:/root/.aws  # Monta las credenciales de AWS en el contenedor
#      - C:/Users/USER/.aws:/root/.aws:ro  # Monta las credenciales de AWS en el contenedor
      - lider_app_data:/home  # Define un volumen llamado 'lider_app_data' montado en '/home' del contenedor
#    deploy:
#          resources:
#            limits:
#              cpus: "0.5"
#              memory: 2G  # Cambiado de 512M a 2G
#            reservations:
#              cpus: "0.25"
#              memory: 512M # Asegura que al menos 512 MB estén disponibles para el contenedor
  bd_posgresql:
    container_name: "lider_bd"
    image: postgres:11
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lider.2025
      POSTGRES_DB: certificadoslider
    volumes:
      - db_data:/var/lib/postgresql/data  # Volumen persistente para los datos de la base de datos
  pgadmin: 
    container_name: "pgadmin_bd"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "lider.2025"
    ports:
      - "3000:80"
    depends_on:
      - bd_posgresql
      
volumes:
  lider_app_data:  # Define el volumen para la aplicación lider_app
  db_data:  # Volumen persistente para los datos de la base de datos
